#See https://aka.ms/overrideVSDockerComposeConfiguration to understand how Visual Studio uses this override file.

version: '3.4'

services:
  web:
    environment:
      - REVOICER_BASE_URL="https://revoicer.azurewebsites.net"
    #labels:
      #com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_web$ \"/app/web.dll\""
      #com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      #com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    entrypoint: tail -f /dev/null
    volumes:
      - ./web:/app
      - ./web:/src
      - C:\Users\pires\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\pires\.nuget\packages\:/root/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/root/.nuget/fallbackpackages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\TokenService.Proxy\linux-x64\net6.0:/TokenService.Proxy:ro  
    tty: true 