version: '3.4'

services:
  
  demucs:
    environment:
      - REVOICER_AZURE_SB_ACCESS_KEY_NAME=Revoicer
      - REVOICER_AZURE_SB_ACCESS_KEY_VALUE=Q39eKIIGssZFxwtHwy0fnt34SAhM5yzJd+ASbO2XqBo=
      - REVOICER_AZURE_SB_ENDPOINT=sb://revoicer.servicebus.windows.net/
      - REVOICER_AZURE_ACCOUNT_NAME=revoicer
      - REVOICER_AZURE_STORAGE_ACCESS_KEY=0V+Dn/QnQ7tRSwaevHymXGtR/UgstoMITdhotUxGRtPDc5/wz+wj7QmQpHqWxP+N7eUI5LzHlwIp+AStdfhaKg==
      - REVOICER_AZURE_STORAGE_CONTAINER_NAME=revoicer
      - REVOICER_INPUT_QUEUE_NAME=revoicer-demucs-input.fifo
      - REVOICER_OUTPUT_QUEUE_NAME=revoicer-demucs-output.fifo
      - REVOICER_DEMUCS_MODEL=htdemucs_6s
      - REVOICER_DEMUCS_EXTRA_PARAMS=--two-stems=vocals
      - REVOICER_DEMUCS_SHIFTS=2
      - REVOICER_DEMUCS_DRIVER=cpu
      - REVOICER_DEMUCS_THREAD_COUNT=12

    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    

  svc:
    environment:
      - REVOICER_AZURE_SB_ACCESS_KEY_NAME=Revoicer
      - REVOICER_AZURE_SB_ACCESS_KEY_VALUE=Q39eKIIGssZFxwtHwy0fnt34SAhM5yzJd+ASbO2XqBo=
      - REVOICER_AZURE_SB_ENDPOINT=sb://revoicer.servicebus.windows.net/
      - REVOICER_AZURE_ACCOUNT_NAME=revoicer
      - REVOICER_AZURE_STORAGE_ACCESS_KEY=0V+Dn/QnQ7tRSwaevHymXGtR/UgstoMITdhotUxGRtPDc5/wz+wj7QmQpHqWxP+N7eUI5LzHlwIp+AStdfhaKg==
      - REVOICER_AZURE_STORAGE_CONTAINER_NAME=revoicer
      - REVOICER_INPUT_QUEUE_NAME=revoicer-svc-input.fifo
      - REVOICER_OUTPUT_QUEUE_NAME=revoicer-svc-output.fifo

    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 4G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    

  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - REVOICER_AZURE_SB_ACCESS_KEY_NAME=Revoicer
      - REVOICER_AZURE_SB_ACCESS_KEY_VALUE=Q39eKIIGssZFxwtHwy0fnt34SAhM5yzJd+ASbO2XqBo=
      - REVOICER_AZURE_SB_ENDPOINT=sb://revoicer.servicebus.windows.net/
      - REVOICER_AZURE_ACCOUNT_NAME=revoicer
      - REVOICER_AZURE_STORAGE_ACCESS_KEY=0V+Dn/QnQ7tRSwaevHymXGtR/UgstoMITdhotUxGRtPDc5/wz+wj7QmQpHqWxP+N7eUI5LzHlwIp+AStdfhaKg==
      - REVOICER_AZURE_STORAGE_CONTAINER_NAME=revoicer
      - REVOICER_REVOICE_INPUT_QUEUE_NAME=revoicer-svc-input.fifo
      - REVOICER_REVOICE_OUTPUT_QUEUE_NAME=revoicer-svc-output.fifo
      - REVOICER_SPLIT_INPUT_QUEUE_NAME=revoicer-demucs-input.fifo
      - REVOICER_SPLIT_OUTPUT_QUEUE_NAME=revoicer-demucs-output.fifo
      - REVOICER_AWS_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=AKIA2WKJWLHNGDV7FA6A
      - AWS_SECRET_ACCESS_KEY=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
      - SSL_CRT_FILE=/root/.aspnet/https/frontend.pem
      - SSL_KEY_FILE=/root/.aspnet/https/frontend.key

    ports:
      - "8080:80"
      - "8443:443"
      - "3000:3000"
      - "1022:22"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./data:/data
