version: '3.4'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
  
  demucs:
    build:
      context: ../workers/demucs      
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=AKIA2WKJWLHNGDV7FA6A
      - AWS_SECRET_ACCESS_KEY=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

    depends_on:
      - localstack
    volumes:
      - ../workers/demucs/app/:/app
      - ./separated:/app/separated
      - ./data:/data
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 16G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    

  ludikore.revoicer.api:
    depends_on:
      - localstack
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - AWS_ACCESS_KEY_ID=AKIA2WKJWLHNGDV7FA6A
      - AWS_SECRET_ACCESS_KEY=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

    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ./data:/data