import asyncio
import os
from abc import ABCMeta
from typing import List, Any

from workers.common.exceptions.RevoicerException import RevoicerException
from workers.common.model.FileInfo import FileInfo
from workers.common.model.RevoicerJob import RevoicerJob
from workers.common.services.QueueBasedService import QueueBasedService

TJob = RevoicerJob
TWorkItem = FileInfo


class RevoicerBaseService(QueueBasedService[TJob, TWorkItem], metaclass=ABCMeta):
    async def load_work_item(self, work_item: TWorkItem) -> TWorkItem:
        """
        The load_work_item function is used to load a work item from the storage service.

        :param self: Represent the instance of the class
        :param work_item: TWorkItem: Pass in the work item to be loaded
        :return: A tworkitem
        """
        return await self.storage_service.get_file(work_item)

    async def store_work_item(self, work_item: TWorkItem):
        """
        The store_work_item function is used to store a work item in the storage service.

        :param self: Represent the instance of the class
        :param work_item: TWorkItem: Store the work item in the storage service
        :return: A future object
        """
        return await self.storage_service.put_file(work_item)


    def preprocess_input_work_item(self, file: Any) -> FileInfo:
        """
        The preprocess_input_work_item function is used to convert the input file into a FileInfo object.
        The FileInfo object contains information about the file, such as its path and name.
        This function is called once for each input file.

        :param self: Represent the instance of a class
        :param file: Any: Pass in the file that is being uploaded
        :return: The file_info object
        """
        # noinspection PyArgumentList
        file_info = FileInfo(str(file), "/" + str(file))
        return file_info

    def preprocess_output_work_item(self, job: TJob, file: Any) -> TWorkItem:
        """
        The preprocess_output_work_item function is called for each output file of the job.
        It returns a FileInfo object that contains the path and content of the file to be uploaded to the
        storage service.
        The path must start with &quot;data/{job_id}/output/&quot;.

        :param self: Represent the instance of the class
        :param job: TJob: Get the operationid of the job
        :param file: Any: Pass the file object to the function
        :return: A fileinfo object
        """
        file_name = os.path.basename(file)
        # noinspection PyArgumentList
        result = FileInfo(f"data/{job.OperationId}/output/{file_name}", file)
        return result

    async def postprocess_output_work_items(self, job: TJob, output_items: List[TWorkItem]) -> List[TWorkItem]:
        """
        The postprocess_output_work_items function is called after the output files are processed.
        It receives a list of TWorkItem objects, which contain information about the local and remote paths of each file.
        The function should return a new list with all items that will be uploaded to the cloud storage.
        In this example, we convert all .wav files to .mp3 using FFMPEG.

        :param self: Access the class attributes and methods
        :param job: TJob: Get the output format from the job
        :param output_items: List[TWorkItem]: Receive the output items that will be generated by the revoicer
        :return: A list of tworkitem objects
        """
        result = []
        tasks = []

        output_format = self.get_output_format(job)

        for original_item in output_items:
            local_filename, extension = os.path.splitext(original_item.LocalPath)
            remote_filename, _ = os.path.splitext(original_item.RemotePath)

            if extension != ".wav":
                continue

            # noinspection PyArgumentList
            converted_item = TWorkItem(
                RemotePath=f"{remote_filename}.{output_format}",
                LocalPath=f"{local_filename}.{output_format}"
            )

            args = ["ffmpeg", "-y", "-i", original_item.LocalPath, "-c:a", output_format, converted_item.LocalPath]
            print(f"Executing FFMPEG with the following arguments: {str(args)}")
            process = await asyncio.create_subprocess_exec(*args)

            result.append(original_item)
            result.append(converted_item)
            tasks.append(process.wait())

        gather_result = await asyncio.gather(*tasks)

        result_code = sum(item for item in gather_result)

        if result_code != 0:
            raise RevoicerException(f"Um ou mais arquivos falharam ao serem convertidos para {output_format}")

        return result

    def get_output_format(self, job: TJob) -> str:
        """
        The get_output_format function takes a job and returns the output format of the files
        to be saved in the storage service.

        :param self: Refer to the class itself
        :param job: TJob: Get the content type of the job
        :return: The output format of the audio file
        """
        match job.ContentType:
            case "audio/mpeg":
                return "mp3"
            case "audio/mpeg4":
                return "aac"
            case "audio/aac":
                return "aac"
            case _:
                return "mp3"
